---
name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: debugprint.nvim
